services:
  db:
    image: postgres:16
    container_name: odoo_db
    environment:
      POSTGRES_DB: gestion_autorisations
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  odoo_app:
    image: odoo:17.0
    container_name: odoo_app
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-filestore:/var/lib/odoo
    command: >
      odoo -d gestion_autorisations -u gestion_des_autorisations
      --db_user=odoo
      --db_password=odoo
      --db_host=db
      --dev=xml

volumes:
  odoo-db-data:
  odoo-filestore:
